###
GET http://localhost:5000/users
Content-Type: application/json

###

###
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "name": "Igor",
    "email": "igor@gmail.com",
    "password": "123456"
}

###